#!/usr/bin/env python

'''
Generate toy events
Can be used for testing steps 2, 3, etc, or producing test MC for e.g. testing reconstruction algorithms

Tom Stuttard
'''

import os, argparse

import numpy as np

from I3Tray import I3Units, I3Tray
from icecube import icetray, dataclasses, dataio, phys_services
from icecube.sim_services.propagation import get_propagators


#
# Functions
#

#TODO put this stuff somewhere common

# List of desired streams
STREAMS = [ icetray.I3Frame.DAQ, icetray.I3Frame.Physics, icetray.I3Frame.TrayInfo, icetray.I3Frame.Simulation ]


def basic_mc_boilerplate(
    tray,
    dataset_num,
    file_num,
    seed=None,
    streamnum=None,
) :
    '''
    Setup common tray cofig used for all MC production
      1) RNG
      2) Event header
    '''

    from globals import max_num_files_per_dataset

    # Defaults
    if seed is None :
        seed = dataset_num
    if streamnum is None :
        streamnum = file_num

    # Set up random number generator
    random_service = phys_services.I3SPRNGRandomService(
        seed=seed,
        nstreams=max_num_files_per_dataset,
        streamnum=streamnum,
    )
    tray.context['I3RandomService'] = random_service

    # Add an event header
    tray.AddModule(
        "I3MCEventHeaderGenerator",
        "gen_header",
        Year=2009,
        DAQTime=158100000000000000,
        RunNumber=file_num,
        # RunNumber=dataset_num,
        # SubrunNumber=file_num,
        EventID=1,
        IncrementEventID=True,
    )

    return random_service


def create_primary(
    frame,
    particle_type,
    energy_GeV,
    pos_x_m,
    pos_y_m,
    pos_z_m,
    coszen,
    azimuth_deg,
    time_ns=0.,
    shape=None,
) :
    '''
    Simple function to create a primary particle in the detector
    and add to the MC tree
    '''

    # Check particle type
    assert hasattr(dataclasses.I3Particle, particle_type), "Unknown particle type : %s" %  particle_type
    particle_type = getattr(dataclasses.I3Particle, particle_type)

    # Create the primary particle
    primary = dataclasses.I3Particle()
    primary.type = particle_type
    primary.energy = energy_GeV * I3Units.GeV
    primary.pos = dataclasses.I3Position(pos_x_m*I3Units.m, pos_y_m*I3Units.m, pos_z_m*I3Units.m)
    primary.dir = dataclasses.I3Direction(np.arccos(coszen), np.deg2rad(azimuth_deg)) # Format: (zenith,azimuth)
    primary.time = time_ns * I3Units.ns
    primary.location_type = dataclasses.I3Particle.InIce

    # Create MC tree and add particles
    tree = dataclasses.I3MCTree()
    tree.add_primary(primary)
    
    # Overwrite shape if user manually specified this
    # If user specified nothing, it defaults to `Primary`
    if shape is not None :
        tree[0].shape = shape

    # Have noticed that CLSim ignores primaries, so warn the user about this in case it is not what they want
    if tree[0].shape == dataclasses.I3Particle.Primary :
        print("WARNING : Particle has shape `Primary`, so will not have photons generated by modern CLSim versions")

    # Add to the frame
    frame["I3MCTree"] = tree


#
# Main
#

if __name__ == "__main__" :

    #
    # Get inputs
    #

    parser = argparse.ArgumentParser()
    parser.add_argument("-n","--num-events",type=int,required=True)
    parser.add_argument("-o","--output-file",type=str,required=True)
    parser.add_argument("-p","--particle",type=str,required=False,default="EMinus")
    parser.add_argument("-e","--energy-GeV",type=float,required=False,default=50.)
    parser.add_argument("-t","--time",type=float,required=False,default=0.)
    parser.add_argument("-x","--pos-x",type=float,required=False,default=46.29) # Default pos is center of DeepCore
    parser.add_argument("-y","--pos-y",type=float,required=False,default=-34.88) # Default pos is center of DeepCore
    parser.add_argument("-z","--pos-z",type=float,required=False,default=-330.0) # Default pos is center of DeepCore
    parser.add_argument("-c","--coszen",type=float,required=False,default=-0.8) # Default is quite up-going
    parser.add_argument("-a","--azimuth-deg",type=float,required=False,default=0.)
    parser.add_argument("-f","--file-num",type=int,required=True)
    parser.add_argument("-d","--dataset-num",type=int,required=True)
    parser.add_argument("--seed",type=int,required=False,default=None)
    parser.add_argument("--streamnum",type=int,required=False,default=None)
    args = parser.parse_args()


    #
    # Run the tray
    #

    tray = I3Tray()

    # Create events
    tray.AddModule("I3InfiniteSource", "infinite_source")

    # Set up basic stuff (RNG, event header)
    random_service = basic_mc_boilerplate(
        tray=tray,
        dataset_num=args.dataset_num,
        file_num=args.file_num,
        seed=args.seed,
        streamnum=args.streamnum,
    )

    # Create particle
    tray.AddModule(
        create_primary,
        "create_primary",
        particle_type=args.particle,
        energy_GeV=args.energy_GeV,
        pos_x_m=args.pos_x,
        pos_y_m=args.pos_y,
        pos_z_m=args.pos_z,
        coszen=args.coszen,
        azimuth_deg=args.azimuth_deg,
        time_ns=args.time,
        streams=[icetray.I3Frame.DAQ],
    )

    # Propogate in the detector
    if args.particle in [ "MuMinus", "MuPlus" ] : #TODO only for muons?
        tray.AddModule('I3PropagatorModule', PropagatorServices=get_propagators(), RandomService=random_service)

    # Tear down
    tray.AddModule('I3Writer', 'writer', streams=STREAMS, filename=args.output_file)
    tray.Execute(args.num_events)
    tray.Finish()

